PKlempe/SAM

- bot/util/utilities.py
> #32: adds echo command

- bot/__main__.py
- bot/admin/admin.py
- bot/constants.py
- bot/university/university.py
> #55: Implement subcommand `cogs` for command `bot` and some bug fixes

- README.md
The text "SAM" is now filled with white instead of being transparent.
> Make the header image more dark mode friendly

- bot/admin/admin.py
- bot/constants.py
- bot/moderation/moderation.py
> #61: Fix the layout of the embed for mobile devices

- bot/util/utilities.py
> #69: Add missing server feature and improve layout

- bot/__main__.py
- bot/admin/admin.py
- bot/university/university.py
> #53: Implement multiple commands for un-/re-/loading cogs

- .gitignore
> #79: Add "logs" directory to .gitignore

- bot/logger/logger.py
> #83: Improve log message formatting

- bot/persistence/database_connector.py
- bot/persistence/queries.py
- bot/role_management/role_management.py
> #115: Add a check if a role has been whitelisted and some log messages

- bot/__main__.py
- bot/singletons.py
- bot/university/university.py
> #114: Replace requests module with async aiohttp

- bot/moderation/moderation.py
- bot/university/university.py
> #122: Fix the sending of mod action infos

- bot/gaming/gaming.py
> #131: Remove "Manage Messages" permission for creator of game room

- bot/gaming/gaming.py
> #133: Handle case when user limit is smaller than 1

- bot/moderation/moderation.py
> #138: Add check which removes unnecessary reactions from modmail

- bot/moderation/moderation.py
> #148: Add placeholder if member doesn't have any roles

- bot/university/university.py
> #150: Fix Copy & Paste error so group exchange will be closed

- bot/university/university.py
> #152: Replace function call with function

- bot/__main__.py
- bot/singletons.py
> #154: Start job scheduler only after Cogs have been loaded

- bot/role_management/role_management.py
> #160: Add check if member already has a unique rr from another message

- bot/music/music.py
> #166: Increase timeout for song playback

- bot/music/music.py
- bot/utility/utility.py
> #172: Use string provided by Discord as feature name if no dict entry

- bot/moderation/moderation.py
> #155: updates modlog for purge and tempmute

- bot/moderation/moderation.py
> Create a scheduler job for removing warnings if a user has been warned

- bot/moderation/moderation.py
> Delete invokation message in error handler of the report command

- bot/constants.py
- bot/utility/utility.py
Some small adjustments regarding the text and representation for `!howto code` and additional custom strings for server features.
> Small improvements

- bot/university/university.py
as self.bot.command_prefix is a function, it leads to ugly output. rather use const.BOT_PREFIX which is a string
> fix message sent to users

- bot/moderation/moderation.py
adds logic to trim role string in userinfo  embed if it is longer than 1024 characters
Closes #244
> #244: adds logic to trim role string in userinfo 

- bot/constants.py
- bot/persistence/database_manager.py
- bot/persistence/in_memory_db.py
> #221: adds in-memory-db functionality

- bot/moderation/moderation.py
> #264: add missing format code for UTC offset

- bot/moderation/moderation.py
> #268: implement answered command
